[package]
name = "controller-passthrough"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gilrs = "0.8.1"
controller-emulator = { version = "*", path = "../controller-emulator" }